using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cohort.Sample.Migrations
{
    /// <inheritdoc />
    public partial class AddRowHandlerDispatch : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                ALTER TABLE "sweep_run_row_detail"
                ADD COLUMN "Id" bigint GENERATED BY DEFAULT AS IDENTITY
                """
            );

            migrationBuilder.DropPrimaryKey(
                name: "PK_sweep_run_row_detail",
                table: "sweep_run_row_detail");

            migrationBuilder.AddColumn<string>(
                name: "CapturedPayload",
                table: "sweep_run_row_detail",
                type: "text",
                nullable: true);

            migrationBuilder.AddPrimaryKey(
                name: "PK_sweep_run_row_detail",
                table: "sweep_run_row_detail",
                column: "Id");

            migrationBuilder.CreateTable(
                name: "sweep_row_handler_status",
                columns: table => new
                {
                    Id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    SweepRunRowDetailId = table.Column<long>(type: "bigint", nullable: false),
                    HandlerType = table.Column<string>(type: "text", nullable: false),
                    State = table.Column<int>(type: "integer", nullable: false),
                    Attempt = table.Column<int>(type: "integer", nullable: false),
                    QueuedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    NextAttemptAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    ClaimedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    CompletedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    LastError = table.Column<string>(type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_sweep_row_handler_status", x => x.Id);
                    table.ForeignKey(
                        name: "FK_sweep_row_handler_status_sweep_run_row_detail_SweepRunRowDe~",
                        column: x => x.SweepRunRowDetailId,
                        principalTable: "sweep_run_row_detail",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_sweep_run_row_detail_SweepId_EntityType_EntityId_Category_S~",
                table: "sweep_run_row_detail",
                columns: new[] { "SweepId", "EntityType", "EntityId", "Category", "Strategy", "TenantId" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_sweep_row_handler_status_State_NextAttemptAt_Id",
                table: "sweep_row_handler_status",
                columns: new[] { "State", "NextAttemptAt", "Id" });

            migrationBuilder.CreateIndex(
                name: "IX_sweep_row_handler_status_SweepRunRowDetailId_HandlerType",
                table: "sweep_row_handler_status",
                columns: new[] { "SweepRunRowDetailId", "HandlerType" },
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "sweep_row_handler_status");

            migrationBuilder.DropPrimaryKey(
                name: "PK_sweep_run_row_detail",
                table: "sweep_run_row_detail");

            migrationBuilder.DropIndex(
                name: "IX_sweep_run_row_detail_SweepId_EntityType_EntityId_Category_S~",
                table: "sweep_run_row_detail");

            migrationBuilder.DropColumn(
                name: "Id",
                table: "sweep_run_row_detail");

            migrationBuilder.DropColumn(
                name: "CapturedPayload",
                table: "sweep_run_row_detail");

            migrationBuilder.AddPrimaryKey(
                name: "PK_sweep_run_row_detail",
                table: "sweep_run_row_detail",
                columns: new[] { "SweepId", "EntityType", "EntityId", "Category", "Strategy", "TenantId" });
        }
    }
}
