// <auto-generated />
using System;
using Cohort.Sample;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cohort.Sample.Migrations
{
    [DbContext(typeof(SampleDbContext))]
    [Migration("20260811080224_MapAnonymisedContactXminConcurrency")]
    partial class MapAnonymisedContactXminConcurrency
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cohort.Infrastructure.Handlers.SweepRowHandlerStatusEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Attempt")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ClaimToken")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DispatchPhase")
                        .HasColumnType("integer");

                    b.Property<string>("HandlerType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("QueuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<long>("SweepRunRowDetailId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SweepRunRowDetailId", "HandlerType")
                        .IsUnique();

                    b.HasIndex("State", "NextAttemptAt", "Id");

                    b.ToTable("sweep_row_handler_status", "public", t =>
                        {
                            t.HasCheckConstraint("CK_sweep_row_handler_status_Claim", "(\"State\" = 1 AND \"ClaimedAt\" IS NOT NULL AND \"ClaimToken\" IS NOT NULL) OR (\"State\" <> 1 AND \"ClaimedAt\" IS NULL AND \"ClaimToken\" IS NULL)");

                            t.HasCheckConstraint("CK_sweep_row_handler_status_Completion", "(\"State\" IN (2, 3) AND \"CompletedAt\" IS NOT NULL) OR (\"State\" IN (0, 1) AND \"CompletedAt\" IS NULL)");
                        });

                    b.HasAnnotation("Cohort:TableRole", "sweep_row_handler_status");
                });

            modelBuilder.Entity("Cohort.Sample.Entities.AnonymisedContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AnonymisedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("text");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("anonymised_contacts", (string)null);
                });

            modelBuilder.Entity("Cohort.Sample.Entities.BlobBackedFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("blob_backed_files", (string)null);
                });

            modelBuilder.Entity("Cohort.Sample.Entities.ErasureSubjectRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("erasure_subject_records", (string)null);
                });

            modelBuilder.Entity("Cohort.Sample.Entities.ExemptDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("exempt_documents", (string)null);
                });

            modelBuilder.Entity("Cohort.Sample.Entities.ExternalNumberedLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExternalId")
                        .HasColumnType("integer");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("external_numbered_logs", (string)null);
                });

            modelBuilder.Entity("Cohort.Sample.Entities.HeldRecord", b =>
                {
                    b.Property<Guid>("HoldId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecordId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("RemovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RetentionEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("HoldId");

                    b.HasIndex("RetentionEntityId", "RecordId");

                    b.HasIndex("RetentionEntityId", "TenantId", "RecordId");

                    b.ToTable("retention_holds", "public");

                    b.HasAnnotation("Cohort:TableRole", "retention_holds");
                });

            modelBuilder.Entity("Cohort.Sample.Entities.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("notes", (string)null);
                });

            modelBuilder.Entity("Cohort.Sample.Entities.NullableAnchorEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("nullable_anchor_events", (string)null);
                });

            modelBuilder.Entity("Cohort.Sample.Entities.PerRowAuditedLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("per_row_audited_logs", (string)null);
                });

            modelBuilder.Entity("Cohort.Sample.Entities.SoftDeleteRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("soft_delete_records", (string)null);
                });

            modelBuilder.Entity("Cohort.Sample.Entities.TenantlessLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("tenantless_logs", (string)null);
                });

            modelBuilder.Entity("Cohort.Sample.Entities.TenantlessSoftDelete", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("tenantless_soft_deletes", (string)null);
                });

            modelBuilder.Entity("Cohort.Sample.Entities.TombstoneRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AnonymisedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("tombstone_records", (string)null);
                });

            modelBuilder.Entity("Cohort.SweepRun", b =>
                {
                    b.Property<Guid>("SweepId")
                        .HasColumnType("uuid");

                    b.Property<bool>("DryRun")
                        .HasColumnType("boolean");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("interval");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("SettledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<long?>("TotalAffected")
                        .HasColumnType("bigint");

                    b.Property<int>("TriggerKind")
                        .HasColumnType("integer");

                    b.HasKey("SweepId");

                    b.ToTable("sweep_run", "public", t =>
                        {
                            t.HasCheckConstraint("CK_sweep_run_Duration_Nonnegative", "\"Duration\" IS NULL OR \"Duration\" >= INTERVAL '0'");

                            t.HasCheckConstraint("CK_sweep_run_Started_Unsettled", "\"Status\" <> 0 OR \"SettledAt\" IS NULL");

                            t.HasCheckConstraint("CK_sweep_run_Status_Range", "\"Status\" BETWEEN 0 AND 4");

                            t.HasCheckConstraint("CK_sweep_run_Terminal_Settled", "\"Status\" = 0 OR \"SettledAt\" IS NOT NULL");

                            t.HasCheckConstraint("CK_sweep_run_TotalAffected_Nonnegative", "\"TotalAffected\" IS NULL OR \"TotalAffected\" >= 0");
                        });

                    b.HasAnnotation("Cohort:TableRole", "sweep_run");
                });

            modelBuilder.Entity("Cohort.SweepRunEntitySummary", b =>
                {
                    b.Property<Guid>("SweepId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RetentionEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Strategy")
                        .HasColumnType("integer");

                    b.Property<long>("Affected")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("HeldCount")
                        .HasColumnType("bigint");

                    b.Property<long>("NullAnchorCount")
                        .HasColumnType("bigint");

                    b.Property<TimeSpan>("ResolvedPeriod")
                        .HasColumnType("interval");

                    b.Property<string>("RuleReason")
                        .HasColumnType("text");

                    b.Property<string>("RuleSource")
                        .HasColumnType("text");

                    b.Property<long>("SkippedCount")
                        .HasColumnType("bigint");

                    b.HasKey("SweepId", "RetentionEntityId", "Category", "TenantId", "Strategy");

                    b.HasIndex("SweepId");

                    b.ToTable("sweep_run_entity_summary", "public");

                    b.HasAnnotation("Cohort:TableRole", "sweep_run_entity_summary");
                });

            modelBuilder.Entity("Cohort.SweepRunRowDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CapturedPayload")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecordId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RetentionEntityId")
                        .HasColumnType("uuid");

                    b.Property<int>("Strategy")
                        .HasColumnType("integer");

                    b.Property<Guid>("SweepId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SweepId");

                    b.HasIndex("SweepId", "RetentionEntityId", "RecordId", "Category", "Strategy", "TenantId")
                        .IsUnique()
                        .HasDatabaseName("IX_sweep_run_row_detail_StableIdentity");

                    b.ToTable("sweep_run_row_detail", "public");

                    b.HasAnnotation("Cohort:TableRole", "sweep_run_row_detail");
                });

            modelBuilder.Entity("Cohort.Infrastructure.Handlers.SweepRowHandlerStatusEntity", b =>
                {
                    b.HasOne("Cohort.SweepRunRowDetail", null)
                        .WithMany()
                        .HasForeignKey("SweepRunRowDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cohort.SweepRunEntitySummary", b =>
                {
                    b.HasOne("Cohort.SweepRun", null)
                        .WithMany()
                        .HasForeignKey("SweepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Cohort.SweepRunRowDetail", b =>
                {
                    b.HasOne("Cohort.SweepRun", null)
                        .WithMany()
                        .HasForeignKey("SweepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
